solution
mate-academy/node_bulls-and-cows pull request #148
Opened 2023-04-27 15:13 UTC by NikitaStambul

2023-04-28 00:18 UTC, Ambulence commented on src/askQuestion.js
> +    const guessedDigits = guessedNumber.split('').map(Number);
I think it would be great to write down the rules of the game here. Something like "You need to guess a number with 4 digits

2023-04-28 00:20 UTC, Ambulence approved these changes
Great job but it would be cool if the player couldn't enter the wrong number.

2023-05-09 17:01 UTC, And678 requested changes
Some things to improve below and this is complete :100:

2023-05-09 17:01 UTC, And678 commented on src/askQuestion.js
> +    }
As per the last requirement, move this `calculating bulls and cows` logic to a separate module

2025-01-19 07:04 UTC, closed without merging